site_name: Code With Engineering Playbook
site_url: https://neoito-hub.github.io/code-with-engineering-playbook
site_description: CSE Code With Engineering Playbook
site_author: NEOITO CSE

repo_url: https://github.com/neoito-hub/code-with-engineering-playbook/
edit_uri: ""

theme:
  name: material
  custom_dir: mkdocs-overrides
  font:
    text: Roboto
  palette:
    primary: black
  logo: resources/neo_logo.jpeg
  favicon: resources/neo_logo.jpeg
  features:
    - navigation.instant
    - navigation.indexes

plugins:
  - search
  - git-revision-date-localized

markdown_extensions:
  - meta
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.pathconverter
  - pymdownx.tabbed
  - mdx_truly_sane_lists
  - pymdownx.tasklist
